"""Generates the ai.yaml configuration reference from the single source of truth: this package's
own `AppConfig` Pydantic schema.

Every section (one per Pydantic model, plus a root section for AppConfig's own top-level fields)
is derived directly from `AppConfig.model_json_schema()` — a new field added to `schema.py` with a
`description=` appears here automatically, with no separate doc to hand-maintain. A field missing
a description renders as "(undocumented)", a visible nudge rather than a silent gap.

Lives in the package (not in scripts/) because `server/monitor.py`'s `lookup_config_reference`
Architect tool imports `render_sections()` at runtime — it must work from an installed `pip
install intagrin`, not just from this source checkout. `scripts/generate_config_reference.py` is
the thin CLI wrapper that writes this module's output to the two committed doc files.
"""

import json

from .schema import AppConfig

ROOT_SECTION_NAME = "AppConfig"


def _ref_name(ref: str) -> str:
    return ref.rsplit("/", 1)[-1]


def _type_str(frag: dict) -> str:
    """Renders one JSON-schema fragment as a short, human-readable type string."""
    if "$ref" in frag:
        return _ref_name(frag["$ref"])
    if "allOf" in frag and len(frag["allOf"]) == 1:
        return _type_str(frag["allOf"][0])
    if "anyOf" in frag:
        parts = [_type_str(p) for p in frag["anyOf"] if p.get("type") != "null"]
        is_optional = any(p.get("type") == "null" for p in frag["anyOf"])
        rendered = " | ".join(dict.fromkeys(parts))
        return f"{rendered} | null" if is_optional else rendered
    if "enum" in frag:
        return " | ".join(json.dumps(v) for v in frag["enum"])
    t = frag.get("type")
    if t == "array":
        return f"list[{_type_str(frag.get('items', {}))}]"
    if t == "object":
        additional = frag.get("additionalProperties")
        if isinstance(additional, dict):
            return f"dict[str, {_type_str(additional)}]"
        return "object"
    return t or "any"


def _default_str(field_name: str, frag: dict, required: set[str]) -> str:
    if field_name in required:
        return "*required*"
    if "default" in frag:
        return f"`{frag['default']!r}`"
    # No explicit default in the schema means Pydantic's default_factory produced it (e.g.
    # default_factory=list/dict) — the schema omits the produced value, so infer a sensible
    # empty-value display from the declared type rather than showing a misleading "None".
    t = frag.get("type")
    if t == "array":
        return "`[]`"
    if t == "object":
        return "`{}`"
    return "(factory default)"


def _render_fields_table(properties: dict, required: set[str]) -> str:
    lines = ["| Field | Type | Default | Description |", "|---|---|---|---|"]
    for field_name, frag in properties.items():
        field_type = _type_str(frag).replace("|", "\\|")
        default = _default_str(field_name, frag, required)
        description = (frag.get("description") or "(undocumented)").replace("\n", " ").replace(
            "|", "\\|"
        )
        lines.append(f"| `{field_name}` | {field_type} | {default} | {description} |")
    return "\n".join(lines)


def render_sections() -> dict[str, str]:
    """One markdown section per Pydantic model (from $defs) plus a root AppConfig section, keyed
    by model name. Used both to assemble the full document and by the Architect's
    lookup_config_reference tool for a single, narrow lookup."""
    schema = AppConfig.model_json_schema()
    defs = schema.get("$defs", {})

    sections: dict[str, str] = {
        ROOT_SECTION_NAME: _render_fields_table(
            schema["properties"], set(schema.get("required", []))
        )
    }
    for model_name in sorted(defs):
        model_schema = defs[model_name]
        sections[model_name] = _render_fields_table(
            model_schema.get("properties", {}), set(model_schema.get("required", []))
        )
    return sections


def render() -> str:
    """Pure function: schema -> full markdown document. No I/O."""
    sections = render_sections()
    intro = (
        "Every field IntaGrin recognizes in `ai.yaml`, grouped by section (one per config "
        "model), generated directly from the Pydantic schema in `src/intagrin/config/schema.py`."
    )
    generated_note = (
        "This file is generated by `scripts/generate_config_reference.py` — do not hand-edit "
        "it. A missing description means the schema field itself needs one, not this file."
    )
    root_note = (
        f"`{ROOT_SECTION_NAME}` below is the root of `ai.yaml`; every other section is a nested "
        "config block referenced from it or from another section."
    )
    lines = [
        "# Configuration Reference",
        "",
        intro,
        "",
        generated_note,
        "",
        root_note,
        "",
    ]
    lines.append(f"## {ROOT_SECTION_NAME}")
    lines.append("")
    lines.append(sections[ROOT_SECTION_NAME])
    lines.append("")
    for name in sorted(k for k in sections if k != ROOT_SECTION_NAME):
        lines.append(f"## {name}")
        lines.append("")
        lines.append(sections[name])
        lines.append("")

    return "\n".join(lines).rstrip() + "\n"
