import json
import sys
from pathlib import Path

from rich.console import Console

from ..compiler.parser import parse_project
from ..config.schema import LocalToolConfig, MCPToolConfig, OpenAPIToolConfig
from ..runtime.tools_loader import get_tool_schema, load_local_tool

console = Console()


STANDALONE_TEMPLATE = '''# Autogenerated Standalone Application from IntaGrin project: __CFG_NAME__
#
# SCOPE: this exports agent '__DEFAULT_AGENT__' — its system prompt and LOCAL tools only.
# Handoffs, delegations, routers, circuit breakers, guardrails, and human-in-the-loop approval
# are NOT included. MCP/OpenAPI tools are NOT included either (no live connection is possible in
# a single zero-dependency file). For the full multi-agent swarm, keep running `inta serve`.
#
# Zero IntaGrin runtime dependency beyond this file's own imports below.
# Run with: uvicorn standalone_app:app --reload

import asyncio
import inspect
import json
import os
from typing import Any
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import litellm

# Tool imports
__TOOL_IMPORTS__

app = FastAPI(title="__CFG_NAME__ (Standalone)", version="__CFG_VERSION__")

MODEL_PRIMARY = "__MODEL_PRIMARY__"
MODEL_FALLBACK = "__MODEL_FALLBACK__"
DEFAULT_AGENT = "__DEFAULT_AGENT__"

# Only DEFAULT_AGENT's prompt is ever used below (there's no handoff mechanism in this export),
# but every agent's prompt is included in case you extend this file by hand.
SYSTEM_PROMPTS = __SYSTEM_PROMPTS_JSON__

# Pre-computed at export time via the real IntaGrin tool reflection — no framework import needed
# at runtime.
TOOL_SCHEMAS = __TOOL_SCHEMAS_JSON__

TOOL_FUNCTIONS = {
__TOOL_FUNCTIONS_ENTRIES__
}

# In-memory session store — lost on restart. Swap in real persistence for anything beyond a demo.
SESSIONS = {}


class ChatRequest(BaseModel):
    session_id: str
    message: str


class ChatResponse(BaseModel):
    response: str
    active_agent: str


async def call_tool(name: str, args: dict) -> str:
    func = TOOL_FUNCTIONS.get(name)
    if func is None:
        return f"Unknown tool: {name}"
    try:
        if inspect.iscoroutinefunction(func):
            result = await func(**args)
        else:
            result = await asyncio.to_thread(func, **args)
        return str(result)
    except Exception as e:
        return f"Tool '{name}' execution failed: {e}"


@app.post("/chat", response_model=ChatResponse)
async def chat(req: ChatRequest):
    session_id = req.session_id
    if session_id not in SESSIONS:
        SESSIONS[session_id] = {"messages": [], "active_agent": DEFAULT_AGENT}

    session = SESSIONS[session_id]
    session["messages"].append({"role": "user", "content": req.message})

    agent = session["active_agent"]
    sys_prompt = SYSTEM_PROMPTS.get(agent, f"You are {agent}.")

    try:
        for _ in range(5):
            current_messages = [{"role": "system", "content": sys_prompt}] + session["messages"]
            kwargs = {
                "model": MODEL_PRIMARY,
                "messages": current_messages,
                "temperature": __MODEL_TEMPERATURE__,
                "max_tokens": __MODEL_MAX_TOKENS__,
            }
            if MODEL_FALLBACK:
                kwargs["fallbacks"] = [{"model": MODEL_FALLBACK}]
            if TOOL_SCHEMAS:
                kwargs["tools"] = TOOL_SCHEMAS
                kwargs["tool_choice"] = "auto"

            resp = await litellm.acompletion(**kwargs)
            msg = resp.choices[0].message

            if msg.tool_calls:
                session["messages"].append(msg.model_dump(exclude_none=True))
                for tc in msg.tool_calls:
                    try:
                        call_args = json.loads(tc.function.arguments or "{}")
                    except Exception:
                        call_args = {}
                    result = await call_tool(tc.function.name, call_args)
                    session["messages"].append(
                        {
                            "role": "tool",
                            "tool_call_id": tc.id,
                            "name": tc.function.name,
                            "content": result,
                        }
                    )
                continue

            reply = msg.content or ""
            session["messages"].append({"role": "assistant", "content": reply})
            return ChatResponse(response=reply, active_agent=agent)

        return ChatResponse(response="[Max tool iterations reached]", active_agent=agent)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)  # nosec B104
'''


class CodeExporter:
    """
    Standalone Code Generator for a single agent.
    Compiles the declarative `ai.yaml`'s default agent — its prompt and local (non-MCP,
    non-OpenAPI) tools — into a pure, self-contained `standalone_app.py` using vanilla FastAPI +
    LiteLLM, with no IntaGrin runtime import required. This is a single-agent export: handoffs,
    delegations, routers, circuit breakers, guardrails, and HITL approval are not reproduced —
    keep running `inta serve` for a real multi-agent swarm.
    """

    def __init__(self, project_dir: Path, output_file: str = "standalone_app.py"):
        self.project_dir = project_dir
        self.output_file = output_file

    def export_fastapi(self):
        graph = parse_project(self.project_dir)
        cfg = graph.config

        console.print(
            f"[bold cyan]📦 Exporting agent '{cfg.default_agent}' from '{cfg.name}' to a standalone FastAPI application...[/bold cyan]"
        )
        console.print(
            f"[dim]Scope: '{cfg.default_agent}''s prompt and local tools only. Handoffs, "
            "delegations, routers, circuit breakers, guardrails, and HITL are not included — "
            "keep using `inta serve` for the full swarm.[/dim]"
        )

        if str(self.project_dir) not in sys.path:
            sys.path.insert(0, str(self.project_dir))

        default_agent_cfg = cfg.agents.get(cfg.default_agent)
        candidate_tools = list(cfg.tools) + (
            list(default_agent_cfg.tools) if default_agent_cfg else []
        )

        tool_imports: list[str] = []
        tool_schemas: list[dict] = []
        tool_function_entries: list[str] = []
        skipped: list[str] = []
        seen_names: set[str] = set()

        for t in candidate_tools:
            if isinstance(t, (MCPToolConfig, OpenAPIToolConfig)):
                skipped.append(f"{t.name} ({'mcp' if isinstance(t, MCPToolConfig) else 'openapi'})")
                continue
            if not isinstance(t, LocalToolConfig) or t.name in seen_names:
                continue
            try:
                func = load_local_tool(t.module, t.name)
                schema = get_tool_schema(func)
            except Exception as e:
                console.print(f"[yellow]⚠ Skipping tool '{t.name}': {e}[/yellow]")
                continue

            seen_names.add(t.name)
            tool_imports.append(f"from {t.module} import {t.name}")
            tool_schemas.append(schema)
            tool_function_entries.append(f'    "{t.name}": {t.name},')

        if skipped:
            console.print(
                f"[yellow]⚠ Not exported (MCP/OpenAPI tools need a live connection, not possible "
                f"in a single file): {', '.join(skipped)}[/yellow]"
            )

        # Read agent prompts (every agent's, in case the file is extended by hand later — see the
        # SYSTEM_PROMPTS comment in the template).
        agent_prompts = {}
        for agent_name, agent_cfg in cfg.agents.items():
            if agent_cfg.system_prompt_file:
                p_path = self.project_dir / agent_cfg.system_prompt_file
                if p_path.exists():
                    agent_prompts[agent_name] = p_path.read_text(encoding="utf-8")
                else:
                    agent_prompts[agent_name] = f"You are {agent_name}."
            else:
                agent_prompts[agent_name] = f"You are {agent_name}."

        replacements = {
            "__CFG_NAME__": cfg.name,
            "__CFG_VERSION__": cfg.version,
            "__DEFAULT_AGENT__": cfg.default_agent,
            "__MODEL_PRIMARY__": cfg.model.primary,
            "__MODEL_FALLBACK__": cfg.model.fallback or "",
            "__MODEL_TEMPERATURE__": repr(cfg.model.temperature),
            "__MODEL_MAX_TOKENS__": repr(cfg.model.max_tokens),
            "__TOOL_IMPORTS__": "\n".join(tool_imports) or "# (no local tools on this agent)",
            "__SYSTEM_PROMPTS_JSON__": json.dumps(agent_prompts, indent=4),
            "__TOOL_SCHEMAS_JSON__": json.dumps(tool_schemas, indent=4),
            "__TOOL_FUNCTIONS_ENTRIES__": "\n".join(tool_function_entries),
        }

        standalone_code = STANDALONE_TEMPLATE
        for token, value in replacements.items():
            standalone_code = standalone_code.replace(token, str(value))

        out_path = self.project_dir / self.output_file
        out_path.write_text(standalone_code, encoding="utf-8")
        console.print(
            f"[bold green]✓ Successfully generated standalone code at: {out_path.name}[/bold green]"
        )
        console.print(
            f"[dim]Exported {len(tool_schemas)} local tool(s) for '{cfg.default_agent}'. "
            "This file has no IntaGrin import, but it is a single-agent export — see the "
            "SCOPE comment at the top of the generated file.[/dim]"
        )
